### ISSUE TITLE
CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by 000rrr** [NVIDIAGameWorks/kaolin#750]
Hi,

I just tried the new kaolin build on windows 10.
`pip install kaolin==0.14.0 -f https://nvidia-kaolin.s3.us-east-2.amazonaws.com/torch-2.0.1_cu118.html`

However, I am getting the following error when calling the chamfer_distance:
`kaolin.metrics.pointcloud.chamfer_distance(pts.unsqueeze(0), inpts.unsqueeze(0)).mean()`

`File "C:\Users\vader\Documents\HML\.venv\Lib\site-packages\kaolin\metrics\pointcloud.py", line 32, in forward
dist, idx = _C.metrics.sided_distance_forward_cuda(p1, p2)
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.`

Any idea how to fix this? Thank you.

**Comment by cytosineXT** [comment]
I have the same error. anybody can help?

**Comment by cytosineXT** [comment]
![微信图片_20240318204753](https://github.com/NVIDIAGameWorks/kaolin/assets/63288867/b123f6ab-2f28-4c4f-a500-87bd63589b00)
I have checked the CUDA version with the torch version, and they are matching and working. But CUDA does not work well on kaolin, I have no idea why is that happening.

**Comment by cytosineXT** [comment]
I have solved it. I changed my GPU from GTX980 to RTX3090 and then the bug magically disappeared.
