### ISSUE TITLE
RuntimeError: cuda runtime error (100) : no CUDA-capable device is detected

### ISSUE THREAD

**Issue by VictorZuanazzi** [NVIDIAGameWorks/kaolin#8]
Hey,

great work with the library!

I am trying to install it, but I am getting a cuda error. I have been using pytorch the gpus wihout problems until now.

The full line reads: `RuntimeError: cuda runtime error (100) : no CUDA-capable device is detected at /opt/conda/conda-bld/pytorch_1570910687650/work/aten/src/THC/THCGeneral.cpp:50`

I am using python 3.7.3 and pytorch 1.3.

the output of nvidia_smi is:
Fri Nov 15 16:13:25 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.56       Driver Version: 418.56       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|==================+======================+======================|
|   0  GeForce GTX TIT...  On   | 00000000:04:00.0 Off |                  N/A |
| 22%   41C    P8    18W / 250W |     11MiB / 12212MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX TIT...  On   | 00000000:06:00.0 Off |                  N/A |
| 22%   38C    P8    17W / 250W |     11MiB / 12212MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 108...  On   | 00000000:07:00.0 Off |                  N/A |
| 31%   34C    P8     8W / 250W |   1283MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX 108...  On   | 00000000:08:00.0 Off |                  N/A |
| 31%   33C    P8     8W / 250W |     10MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  TITAN X (Pascal)    On   | 00000000:0C:00.0 Off |                  N/A |
| 23%   35C    P8     8W / 250W |     10MiB / 12196MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  TITAN X (Pascal)    On   | 00000000:0E:00.0 Off |                  N/A |
| 23%   30C    P8     8W / 250W |     10MiB / 12196MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|============================================================|
|    2     14534      C   ...zzi/anaconda3/envs/tmtm/bin/python3.7  1273MiB |
+-----------------------------------------------------------------------------+

Any suggestions?

**Comment by VictorZuanazzi** [comment]
Problem solved. 

I had to specify an GPU for the installer` export CUDA_VISIBLE_DEVICES=2`

**Comment by Haveoneriver** [comment]
@VictorZuanazzi Hi I have encountered the same problem. Can you elaborate on your solution?thanks

**Comment by Perenn1s** [comment]
Thank you. I specified the device and solved

**Comment by VictorZuanazzi** [comment]
@Haveoneriver , before installing the package explicitly specify the gpu you want to install it. I recomend using the same gpu to install as the one you will run things in the future, there is plenty of problems that come when using different gpus. 
`export CUDA_VISIBLE_DEVICES=X`, where X is the device, if you only have one gpu, use zero.

**Comment by umerhasan17** [comment]
Just to expand on the previous comment, this is the command that worked for me: 
`CUDA_VISIBLE_DEVICES=2 python file.py` 
instead of `python file.py`

**Comment by sandeep22-v** [comment]
Where should I add CUDA_VISIBLE_DEVICES=2 ???in the terminal or in some python file???

**Comment by Hiram9270** [comment]
so where can we find this line" export CUDA_VISIBLE_DEVICES=X"?thanks

**Comment by ziyue-zhang27** [comment]
> so where can we find this line" export CUDA_VISIBLE_DEVICES=X"?thanks

I meet the same problem, did you solve it? Where did you add CUDA_VISIBLE_DEVICES=X?

**Comment by ziyue-zhang27** [comment]
> Where should I add CUDA_VISIBLE_DEVICES=2 ???in the terminal or in some python file???

I meet the same problem, did you solve it? Where did you add CUDA_VISIBLE_DEVICES=X?

**Comment by AnushaSwamy-95** [comment]
In Windows Terminal, Add this line to set your CUDA Visible device : set CUDA_VISIBLE_DEVICES=0 (0 because I have 1 available GPU )

**Comment by seanreynoldscs** [comment]
If running in python rather than terminal just put this at the top:
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
