### ISSUE TITLE
Kaolin incopatibility with V100 and Kepler gpu models.

### ISSUE THREAD

**Issue by VictorZuanazzi** [NVIDIAGameWorks/kaolin#96]
Hello,

I am trying to use the library for different experiments. I found that some of the Cuda code does not seem compatible with all Nvidia GPUs. From my experiments I found that:

- Kepler, GeForce GTX Titan: **Not Compatible**
- Pascal, GeForce GTX 1080 Ti:: Compatible
- Pascal, TITAN X (Pascal): Compatible
- Volta, V100: **Not Compatible**

My setup is:
Python 3.6.9
CUDA 10.1
Ubuntu 16.04.5
Pytorch 1.3.1

In my particular case, I am trying to use Pointnet2 Functions. For instance, when I call the FlowEmbedding layer I get the following error message:
 `CUDA kernel failed : no kernel image is available for execution on the device
void query_ball_random_point_kernel_launcher(int, int, int, int, float, int, const float*, const float*, int*) at L:153 in kaolin/cuda/ball_query_cuda.cu
`
Any chance the problem is due to the installation?

**Comment by VictorZuanazzi** [comment]
Those were my installation steps:
`$ conda create -n v100 python=3.6.9 anaconda`
`$ conda activate v100`
`$ conda install pytorch torchvision cudatoolkit=10.1 -c pytorch`
`$ conda install -c anaconda cython`
`$ pip install torchsummary` 
`cd kaolin`
`$ python setup.py build_ext --inplace`
`$ python setup.py install`
`$ source setenv.sh`
`$ pytest tests/`
Results from the tests:
```
===================================================================================================================== test session starts =====================================================================================================================
platform linux -- Python 3.6.9, pytest-5.2.1, py-1.8.0, pluggy-0.13.0
rootdir: /home/zuanazzi/PointCloudFlow/kaolin
plugins: openfiles-0.4.0, remotedata-0.3.2, arraydiff-0.3, doctestplus-0.4.0, cov-2.8.1
collected 163 items                                                                                                                                                                                                                                           

tests/test_import.py ....                                                                      [  2%]
tests/conversions/test_meshconversions.py .....F                             [  6%]
tests/conversions/test_pointcloudconversions.py FFF                      [  7%]
tests/conversions/test_sdfconversions.py ...                                     [  9%]
tests/conversions/test_voxelgridconversions.py .......F                     [ 14%]
tests/datasets/test_usdfile.py .                                                          [ 15%]
tests/mathutils/test_common.py .......                                                [ 19%]
tests/mathutils/test_transformations.py ...........                                 [ 26%]
tests/metrics/test_mesh_metrics.py ....F..F                                       [ 31%]
tests/metrics/test_point_metrics.py ....FF.F                                       [ 36%]
tests/metrics/test_voxel_metrics.py ..                                                [ 37%]
tests/models/test_PointNet.py .                                                         [ 38%]
tests/models/test_PointNet2.py 
```

**Comment by VictorZuanazzi** [comment]
Problem solved.

That is what I have done:

1. pulled the last version of this repo
2. installed kaolin using one of the problematic GPUs (in my case, the v100)
3. the installation followed the exact same steps as here: https://github.com/NVIDIAGameWorks/kaolin/issues/96#issuecomment-566004900
4. hurray it worked!

**Comment by Zhangsihao-Yang** [comment]
> Problem solved.
> 
> That is what I have done:
> 
> 1. pulled the last version of this repo
> 2. installed kaolin using one of the problematic GPUs (in my case, the v100)
> 3. the installation followed the exact same steps as here: [#96 (comment)](https://github.com/NVIDIAGameWorks/kaolin/issues/96#issuecomment-566004900)
> 4. hurray it worked!

Would you like to explain how do you do the first and second steps? Appreciate that.
